export const VIDEO_URLS: Record<number, string[]> = {
  1: ["https://www.youtube.com/watch?v=UdClWpczMCI", 
      "https://www.youtube.com/watch?v=WX0qk_YXrl4", 
      "https://www.youtube.com/watch?v=KQW4hoM95v4", 
      "https://www.youtube.com/watch?v=jqtT1jfjRHs", 
      "https://www.youtube.com/watch?v=Lye6aOyh7Xs",
      "https://www.youtube.com/watch?v=BhwfwmUDXqI", 
      "https://www.youtube.com/watch?v=ZXUh7Xat6Rw", 
      "https://www.youtube.com/watch?v=up0OmGFkUkg", 
      "https://www.youtube.com/watch?v=dlow5vmO-14", 
      "https://www.youtube.com/watch?v=a7gVubkOg-Q", 
      "https://www.youtube.com/watch?v=W1QchPQSSlI",
      "https://www.youtube.com/watch?v=OG_h2vDn3So",
    ],
  2: ["https://www.youtube.com/watch?v=eLBJzkkZY-o", 
      "https://www.youtube.com/watch?v=d0h8nVosWKs", 
      "https://www.youtube.com/watch?v=u_Z6pYrv8ss", 
      "https://www.youtube.com/watch?v=d6_7QR7PQqQ", 
      "https://www.youtube.com/watch?v=k7cF71Z8zB4",
      "https://www.youtube.com/watch?v=8r0FpakQmcs", 
      "https://www.youtube.com/watch?v=mEcT4bW-Hg0", 
      "https://www.youtube.com/watch?v=yhIim9S2dB0", 
      "https://www.youtube.com/watch?v=lrtwpCD8o-w", 
      "https://www.youtube.com/watch?v=wsQyP2vHtwU", 
      "https://www.youtube.com/watch?v=-i8pCXSHCTU",
      "https://www.youtube.com/watch?v=Y6fY257dR3k",
    ],
  3: ["https://www.youtube.com/watch?v=iXDAqjJRC2c", 
      "https://www.youtube.com/watch?v=iXDAqjJRC2c", 
      "https://www.youtube.com/watch?v=PpW9wvxJJS8", 
      "https://www.youtube.com/watch?v=WmTB_wv1734", 
      "https://www.youtube.com/watch?v=iXDAqjJRC2c&t=5s",
      "https://www.youtube.com/watch?v=Mlw2KOYRk64", 
      "https://www.youtube.com/watch?v=HqyV1uPWrfY", 
      "https://www.youtube.com/watch?v=UVbrNhaXoZc", 
      "https://www.youtube.com/watch?v=iqDZH5-auZQ", 
      "https://www.youtube.com/watch?v=QEkgZ7kFRxo", 
      "https://www.youtube.com/watch?v=muro2AN-JMU",
      "https://www.youtube.com/watch?v=QEkgZ7kFRxo&t=3s",
    ],
  4: ["https://www.youtube.com/watch?v=UdClWpczMCI", 
      "https://www.youtube.com/watch?v=qITQwPlS6A8", 
      "https://www.youtube.com/watch?v=UiQ_mdxLMYg", 
      "https://www.youtube.com/watch?v=_-DD2mJGqn0", 
      "https://www.youtube.com/watch?v=_DGHxCOhVjc", 
      "https://www.youtube.com/watch?v=VhZ6YOpSEFU",
      "https://www.youtube.com/watch?v=YRg0w_5SCdM", 
      "https://www.youtube.com/watch?v=feOVz1Fkp2g", 
      "https://www.youtube.com/watch?v=-YLsiDQBrK8", 
      "https://www.youtube.com/watch?v=_AcMGGHNoLY", 
      "https://www.youtube.com/watch?v=P2zGhgMYyrA",
      "https://www.youtube.com/watch?v=rCt3QBXEZ3E",
    ],
}